### ISSUE TITLE
How to create a (Postgres) array from a JsonObject?

### ISSUE THREAD

**Issue by thokari** [vert-x3/vertx-sql-common#17]
Hi, 
So I ran into this problem, that with JDBC, the creation of an SQL array expression is vendor specific, as suggested by existence this method https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#createArrayOf(java.lang.String,%20java.lang.Object[])
and this thread:
http://stackoverflow.com/questions/18658107/binding-parameter-as-postgresql-array
How would I work around this with postgres, with the JDBCClient of vertx? If I wanted to use `updateWithParams`, how should I supply the parameters, in case one is an array?

**Comment by thokari** [comment]
```
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of io.vertx.core.json.JsonArray. Use setObject() with an explicit Types value to specify the type to use.
    at org.postgresql.jdbc.PgStatement.setObject(PgStatement.java:1871)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setObject(NewProxyPreparedStatement.java:852)
    at io.vertx.ext.jdbc.impl.actions.JDBCStatementHelper.fillStatement(JDBCStatementHelper.java:51)
    at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.execute(JDBCUpdate.java:48)
    at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.execute(JDBCUpdate.java:34)
    at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:48)
    at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:33)
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$15(ContextImpl.java:296)
    at io.vertx.core.impl.ContextImpl$$Lambda$25/2087258327.run(Unknown Source)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$261(OrderedExecutorFactory.java:91)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$21/25536233.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by thokari** [comment]
If I start messing around with building strings, which I want to avoid in the first place, I get this:

```
org.postgresql.util.PSQLException: ERROR: column "permissions" is of type character varying[] but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 103
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:622)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:472)
    at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:429)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:410)
    at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.execute(JDBCUpdate.java:50)
    at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.execute(JDBCUpdate.java:34)
    at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:48)
    at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:33)
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$15(ContextImpl.java:296)
    at io.vertx.core.impl.ContextImpl$$Lambda$25/2087258327.run(Unknown Source)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$261(OrderedExecutorFactory.java:91)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$21/25536233.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Also, would that somehow be a non issue, if I switched to the async vertx-postgres-mysql?
Judging from the API it wouldn't unless I am overlooking it.

**Comment by pmlopes** [comment]
See: https://github.com/vert-x3/vertx-jdbc-client/tree/issues/issue-17

This PR seems to solve the issue but it is Postgres specific. The problem that is hard to solve here is how to handle empty arrays. The jdbc API expects a type when creating an array even if empty, in postgres we can work around this by specifying `oid` since it is just a pointer array without elements it is fine. But will not work with Oracle for example.

**Comment by a-marcel** [comment]
Till the fix is ready, you can use

```
String[] tagArray = { "tag1", "tag2"};


// please check if no empty values in it
StringBuilder tags = new StringBuilder();
tags.append("{\"");
tags.append(StringUtils.join(tagArray, "\",\""));
tags.append("\"}");


String sql = "Insert into x (tags) values (?::text[])";


JsonArray params = new JsonArray();
params.add(tags);


conn.updateWithParams(sql params, res -> {});
```

Marcel

**Comment by thokari** [comment]
Thanks for getting back to me! I will check it out.

**Comment by joao-rebelo** [comment]
Would it be reasonable that Vert.x takes a JsonArray and converts it into a "native"/sql Array while preparing the statements?
maybe we would need to somehow provide the datatype for the array..

any solution for Oracle using Vertx, other than adding '?' to the query ?

**Comment by pmlopes** [comment]
The issue is that jdbc arrays require to know the type at creation time, but json arrays can hold anything, also null and empty arrays are not enough to try to guess the content type.

**Comment by joao-rebelo** [comment]
Any way that the API would let the user manipulate how the parameters are added?
Allowing to pass some Handler / Consumer that gets the param JsonArray at an index, and the Statement in order to adapt the value?

**Comment by pmlopes** [comment]
The preferred way to do Postgres with full support for any types is using the new https://github.com/eclipse-vertx/vertx-sql-client
